/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5p2_juanmembreno;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author usuario
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JDialog();
        user = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbingresar = new javax.swing.JButton();
        contra = new javax.swing.JTextField();
        jbnuevo = new javax.swing.JButton();
        ingresar = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        apellidodo = new javax.swing.JTextField();
        titulaciondo = new javax.swing.JTextField();
        nombredo = new javax.swing.JTextField();
        cantalumnosdo = new javax.swing.JTextField();
        nombreclasedo = new javax.swing.JTextField();
        usuariodo = new javax.swing.JTextField();
        titulacionmdo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        contrasenado = new javax.swing.JTextField();
        descripciondo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ingresarceo = new javax.swing.JDialog();
        apellidoc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        idc = new javax.swing.JTextField();
        nombrec = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        anosc = new javax.swing.JTextField();
        edadc = new javax.swing.JTextField();
        titulacionc = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        usuarioc = new javax.swing.JTextField();
        contrasenac = new javax.swing.JTextField();
        ingresardecano = new javax.swing.JDialog();
        contrasenade = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        titulacionude = new javax.swing.JTextField();
        edade = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        titulacionde = new javax.swing.JTextField();
        idde = new javax.swing.JTextField();
        nombrede = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        usuariode = new javax.swing.JTextField();
        apellidode = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        titulacionmde = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        ingresaralumno = new javax.swing.JDialog();
        jLabel24 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        carreraa = new javax.swing.JTextField();
        numeroa = new javax.swing.JTextField();
        anoa = new javax.swing.JTextField();
        apellidoa = new javax.swing.JTextField();
        usuarioa = new javax.swing.JTextField();
        contrasenaa = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        canta = new javax.swing.JTextField();
        nombrea1 = new javax.swing.JTextField();
        alumnos = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jla = new javax.swing.JList<>();
        aplicarprueba = new javax.swing.JPopupMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        vernota = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        modificaralumno = new javax.swing.JDialog();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        apellidoa2 = new javax.swing.JTextField();
        edada2 = new javax.swing.JTextField();
        nocuentaa2 = new javax.swing.JTextField();
        nombrea2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        listar = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtreedecano = new javax.swing.JTree();
        crud = new javax.swing.JPopupMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        modificardocente = new javax.swing.JDialog();
        jLabel47 = new javax.swing.JLabel();
        contrasenado1 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        descripciondo1 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        apellidodo1 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        titulaciondo1 = new javax.swing.JTextField();
        nombredo1 = new javax.swing.JTextField();
        cantalumnosdo1 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        nombreclasedo1 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        usuariodo1 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        titulacionmdo1 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();

        jLabel1.setText("Login");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contrasena");

        jbingresar.setText("Ingresar ");
        jbingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbingresarMouseClicked(evt);
            }
        });

        jbnuevo.setText("Nuevo Usuario");
        jbnuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbnuevoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login.getContentPane());
        login.getContentPane().setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(195, 195, 195))
            .addGroup(loginLayout.createSequentialGroup()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jbingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jbnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jbingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jLabel4.setText("Docente");

        jLabel5.setText("Nombre");

        jLabel6.setText("Apellido");

        jLabel7.setText("Titulacion P");

        jLabel8.setText("Titulacion maestria");

        jLabel9.setText("Cant alumnos");

        jLabel10.setText("Nombre clase");

        jLabel11.setText("Descripcion");

        titulaciondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titulaciondoActionPerformed(evt);
            }
        });

        jButton1.setText("Registrar Docente ");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel12.setText("Usuario");

        jLabel13.setText("Contrassena");

        javax.swing.GroupLayout ingresarLayout = new javax.swing.GroupLayout(ingresar.getContentPane());
        ingresar.getContentPane().setLayout(ingresarLayout);
        ingresarLayout.setHorizontalGroup(
            ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ingresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(ingresarLayout.createSequentialGroup()
                .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ingresarLayout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jLabel4))
                    .addGroup(ingresarLayout.createSequentialGroup()
                        .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ingresarLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)))
                            .addGroup(ingresarLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))))
                        .addGap(54, 54, 54)
                        .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulaciondo, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellidodo, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantalumnosdo, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreclasedo, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titulacionmdo, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombredo, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descripciondo, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuariodo, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ingresarLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(contrasenado, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        ingresarLayout.setVerticalGroup(
            ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ingresarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addGap(59, 59, 59)
                .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nombredo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ingresarLayout.createSequentialGroup()
                        .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ingresarLayout.createSequentialGroup()
                                .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(apellidodo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addComponent(jLabel7))
                            .addComponent(titulaciondo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addComponent(jLabel8))
                    .addComponent(titulacionmdo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cantalumnosdo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nombreclasedo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(descripciondo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuariodo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contrasenado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(86, 86, 86)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel14.setText("Nombre");

        idc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idcActionPerformed(evt);
            }
        });

        jLabel15.setText("Apellido");

        jLabel16.setText("Titulacion P");

        jLabel17.setText("Ceo");

        jLabel18.setText("Id");

        jLabel19.setText("Anos Ex\\");

            jLabel20.setText("Edad");

            anosc.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    anoscActionPerformed(evt);
                }
            });

            edadc.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    edadcActionPerformed(evt);
                }
            });

            titulacionc.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    titulacioncActionPerformed(evt);
                }
            });

            jButton2.setText("Ingresar CEO");
            jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton2MouseClicked(evt);
                }
            });

            jLabel21.setText("Usuario");

            jLabel22.setText("Contrassena");

            javax.swing.GroupLayout ingresarceoLayout = new javax.swing.GroupLayout(ingresarceo.getContentPane());
            ingresarceo.getContentPane().setLayout(ingresarceoLayout);
            ingresarceoLayout.setHorizontalGroup(
                ingresarceoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ingresarceoLayout.createSequentialGroup()
                    .addGroup(ingresarceoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ingresarceoLayout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addGroup(ingresarceoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ingresarceoLayout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addGroup(ingresarceoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel14)))
                                .addComponent(jLabel16)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20))
                            .addGap(54, 54, 54)
                            .addGroup(ingresarceoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(idc, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(apellidoc, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nombrec, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(anosc, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(edadc, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(titulacionc, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(ingresarceoLayout.createSequentialGroup()
                            .addGap(381, 381, 381)
                            .addComponent(jLabel17))
                        .addGroup(ingresarceoLayout.createSequentialGroup()
                            .addGap(336, 336, 336)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ingresarceoLayout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addGroup(ingresarceoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ingresarceoLayout.createSequentialGroup()
                                    .addGroup(ingresarceoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel22))
                                    .addGap(54, 54, 54)
                                    .addComponent(usuarioc, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ingresarceoLayout.createSequentialGroup()
                                    .addGap(150, 150, 150)
                                    .addComponent(contrasenac, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(360, Short.MAX_VALUE))
            );
            ingresarceoLayout.setVerticalGroup(
                ingresarceoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ingresarceoLayout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(jLabel17)
                    .addGap(82, 82, 82)
                    .addGroup(ingresarceoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(nombrec, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(ingresarceoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(apellidoc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(37, 37, 37)
                    .addGroup(ingresarceoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(titulacionc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(31, 31, 31)
                    .addGroup(ingresarceoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(idc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(46, 46, 46)
                    .addGroup(ingresarceoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(anosc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(35, 35, 35)
                    .addGroup(ingresarceoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel20)
                        .addComponent(edadc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(36, 36, 36)
                    .addGroup(ingresarceoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(usuarioc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                    .addGroup(ingresarceoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(contrasenac, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22))
                    .addGap(48, 48, 48)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(102, 102, 102))
            );

            jLabel23.setText("Id");

            jLabel25.setText("Edad");

            edade.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    edadeActionPerformed(evt);
                }
            });

            jLabel26.setText("Nombre");

            titulacionde.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    titulaciondeActionPerformed(evt);
                }
            });

            idde.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    iddeActionPerformed(evt);
                }
            });

            jLabel27.setText("Usuario");

            jLabel28.setText("Apellido");

            jLabel29.setText("Contrassena");

            jLabel30.setText("Titulacion P");

            usuariode.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    usuariodeActionPerformed(evt);
                }
            });

            jLabel31.setText("Titulo Uni");

            jLabel32.setText("Titulo Mestria");

            jLabel33.setText("DEcano ");

            jButton3.setText("Crear decano ");
            jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton3MouseClicked(evt);
                }
            });

            javax.swing.GroupLayout ingresardecanoLayout = new javax.swing.GroupLayout(ingresardecano.getContentPane());
            ingresardecano.getContentPane().setLayout(ingresardecanoLayout);
            ingresardecanoLayout.setHorizontalGroup(
                ingresardecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ingresardecanoLayout.createSequentialGroup()
                    .addGroup(ingresardecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ingresardecanoLayout.createSequentialGroup()
                            .addGap(101, 101, 101)
                            .addGroup(ingresardecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ingresardecanoLayout.createSequentialGroup()
                                    .addComponent(jLabel27)
                                    .addGap(106, 106, 106)
                                    .addComponent(usuariode, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(97, 97, 97)
                                    .addComponent(jButton3))
                                .addGroup(ingresardecanoLayout.createSequentialGroup()
                                    .addGroup(ingresardecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(ingresardecanoLayout.createSequentialGroup()
                                            .addGap(9, 9, 9)
                                            .addGroup(ingresardecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(ingresardecanoLayout.createSequentialGroup()
                                                    .addGap(8, 8, 8)
                                                    .addGroup(ingresardecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel28)
                                                        .addComponent(jLabel26)))
                                                .addComponent(jLabel30)
                                                .addComponent(jLabel23)
                                                .addComponent(jLabel25)
                                                .addComponent(jLabel31)))
                                        .addComponent(jLabel32))
                                    .addGap(54, 54, 54)
                                    .addGroup(ingresardecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(titulacionmde, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(idde, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(titulacionude, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nombrede, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(edade, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(titulacionde, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(apellidode, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(ingresardecanoLayout.createSequentialGroup()
                            .addGap(348, 348, 348)
                            .addComponent(jLabel33)))
                    .addContainerGap(82, Short.MAX_VALUE))
                .addGroup(ingresardecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ingresardecanoLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(ingresardecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addGroup(ingresardecanoLayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(contrasenade, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(295, Short.MAX_VALUE)))
            );
            ingresardecanoLayout.setVerticalGroup(
                ingresardecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ingresardecanoLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jLabel33)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                    .addGroup(ingresardecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(nombrede, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(ingresardecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(apellidode, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(37, 37, 37)
                    .addGroup(ingresardecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(titulacionde, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(31, 31, 31)
                    .addGroup(ingresardecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(idde, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(44, 44, 44)
                    .addGroup(ingresardecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25))
                    .addGap(18, 18, 18)
                    .addGroup(ingresardecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(titulacionude, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel31))
                    .addGap(22, 22, 22)
                    .addGroup(ingresardecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ingresardecanoLayout.createSequentialGroup()
                            .addComponent(jLabel32)
                            .addGap(42, 42, 42)
                            .addGroup(ingresardecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(usuariode, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel27)))
                        .addGroup(ingresardecanoLayout.createSequentialGroup()
                            .addComponent(titulacionmde, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)
                            .addComponent(jButton3)))
                    .addGap(59, 59, 59))
                .addGroup(ingresardecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ingresardecanoLayout.createSequentialGroup()
                        .addContainerGap(622, Short.MAX_VALUE)
                        .addGroup(ingresardecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contrasenade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addContainerGap()))
            );

            jLabel24.setText("alumno");

            jLabel34.setText("Nombre");

            jLabel35.setText("Apellido");

            jLabel36.setText("No  Cuenta");

            jLabel37.setText("Ano de la carrera que cursa");

            jLabel38.setText("cantidad de clases faltantes");

            jLabel39.setText("Usuario");

            jLabel40.setText("Contrasena");

            jButton5.setText("Ingresar Alumno");
            jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton5MouseClicked(evt);
                }
            });

            jLabel41.setText("Carrera");

            canta.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cantaActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout ingresaralumnoLayout = new javax.swing.GroupLayout(ingresaralumno.getContentPane());
            ingresaralumno.getContentPane().setLayout(ingresaralumnoLayout);
            ingresaralumnoLayout.setHorizontalGroup(
                ingresaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ingresaralumnoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButton5)
                    .addGap(232, 232, 232))
                .addGroup(ingresaralumnoLayout.createSequentialGroup()
                    .addGroup(ingresaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ingresaralumnoLayout.createSequentialGroup()
                            .addGap(292, 292, 292)
                            .addComponent(jLabel24))
                        .addGroup(ingresaralumnoLayout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addGroup(ingresaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel35)
                                .addComponent(jLabel34)
                                .addGroup(ingresaralumnoLayout.createSequentialGroup()
                                    .addGroup(ingresaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel37)
                                        .addComponent(jLabel38))
                                    .addGroup(ingresaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(ingresaralumnoLayout.createSequentialGroup()
                                            .addGap(37, 37, 37)
                                            .addComponent(anoa, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(ingresaralumnoLayout.createSequentialGroup()
                                            .addGap(48, 48, 48)
                                            .addComponent(canta, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(ingresaralumnoLayout.createSequentialGroup()
                                    .addComponent(jLabel36)
                                    .addGap(117, 117, 117)
                                    .addComponent(numeroa, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ingresaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ingresaralumnoLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel41)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(carreraa, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ingresaralumnoLayout.createSequentialGroup()
                                        .addComponent(jLabel39)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(usuarioa, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ingresaralumnoLayout.createSequentialGroup()
                                        .addComponent(jLabel40)
                                        .addGap(124, 124, 124)
                                        .addComponent(contrasenaa, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addContainerGap(149, Short.MAX_VALUE))
                .addGroup(ingresaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ingresaralumnoLayout.createSequentialGroup()
                        .addContainerGap(243, Short.MAX_VALUE)
                        .addComponent(apellidoa, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)))
                .addGroup(ingresaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ingresaralumnoLayout.createSequentialGroup()
                        .addContainerGap(231, Short.MAX_VALUE)
                        .addComponent(nombrea1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192)))
            );
            ingresaralumnoLayout.setVerticalGroup(
                ingresaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ingresaralumnoLayout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(jLabel24)
                    .addGap(47, 47, 47)
                    .addComponent(jLabel34)
                    .addGap(65, 65, 65)
                    .addComponent(jLabel35)
                    .addGap(43, 43, 43)
                    .addGroup(ingresaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel36)
                        .addComponent(numeroa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(43, 43, 43)
                    .addGroup(ingresaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel37)
                        .addComponent(anoa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(ingresaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel38)
                        .addComponent(canta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(ingresaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel41)
                        .addComponent(carreraa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(19, 19, 19)
                    .addGroup(ingresaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(usuarioa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel39))
                    .addGap(34, 34, 34)
                    .addGroup(ingresaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel40)
                        .addComponent(contrasenaa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                    .addComponent(jButton5)
                    .addGap(28, 28, 28))
                .addGroup(ingresaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ingresaralumnoLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(apellidoa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(547, Short.MAX_VALUE)))
                .addGroup(ingresaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ingresaralumnoLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(nombrea1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(626, Short.MAX_VALUE)))
            );

            jla.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = { " " };
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
            jla.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jlaMouseClicked(evt);
                }
            });
            jScrollPane1.setViewportView(jla);

            javax.swing.GroupLayout alumnosLayout = new javax.swing.GroupLayout(alumnos.getContentPane());
            alumnos.getContentPane().setLayout(alumnosLayout);
            alumnosLayout.setHorizontalGroup(
                alumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(alumnosLayout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(92, Short.MAX_VALUE))
            );
            alumnosLayout.setVerticalGroup(
                alumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(alumnosLayout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(81, Short.MAX_VALUE))
            );

            jMenuItem4.setText("Aplicar Prueba");
            jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jMenuItem4MouseClicked(evt);
                }
            });
            jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem4ActionPerformed(evt);
                }
            });
            aplicarprueba.add(jMenuItem4);

            tabla1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Nombre del Maestro que la Ingreso", "Resultado"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
            });
            jScrollPane2.setViewportView(tabla1);

            javax.swing.GroupLayout vernotaLayout = new javax.swing.GroupLayout(vernota.getContentPane());
            vernota.getContentPane().setLayout(vernotaLayout);
            vernotaLayout.setHorizontalGroup(
                vernotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(vernotaLayout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(70, Short.MAX_VALUE))
            );
            vernotaLayout.setVerticalGroup(
                vernotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(vernotaLayout.createSequentialGroup()
                    .addGap(144, 144, 144)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(163, Short.MAX_VALUE))
            );

            jLabel42.setText("Modificar Info");

            jLabel43.setText("Nombre");

            jLabel44.setText("Apellido");

            jLabel45.setText("edad");

            jLabel46.setText("no cuenta");

            jButton4.setText("modificar");

            javax.swing.GroupLayout modificaralumnoLayout = new javax.swing.GroupLayout(modificaralumno.getContentPane());
            modificaralumno.getContentPane().setLayout(modificaralumnoLayout);
            modificaralumnoLayout.setHorizontalGroup(
                modificaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(modificaralumnoLayout.createSequentialGroup()
                    .addGroup(modificaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(modificaralumnoLayout.createSequentialGroup()
                            .addGap(335, 335, 335)
                            .addComponent(jLabel42))
                        .addGroup(modificaralumnoLayout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addGroup(modificaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel43)
                                .addGroup(modificaralumnoLayout.createSequentialGroup()
                                    .addGroup(modificaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel44)
                                        .addComponent(jLabel45)
                                        .addComponent(jLabel46))
                                    .addGap(90, 90, 90)
                                    .addGroup(modificaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nocuentaa2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(edada2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(apellidoa2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(modificaralumnoLayout.createSequentialGroup()
                            .addGap(277, 277, 277)
                            .addComponent(jButton4)))
                    .addContainerGap(339, Short.MAX_VALUE))
                .addGroup(modificaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificaralumnoLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(nombrea2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(315, Short.MAX_VALUE)))
            );
            modificaralumnoLayout.setVerticalGroup(
                modificaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(modificaralumnoLayout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addComponent(jLabel42)
                    .addGap(50, 50, 50)
                    .addComponent(jLabel43)
                    .addGap(53, 53, 53)
                    .addGroup(modificaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel44)
                        .addComponent(apellidoa2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(58, 58, 58)
                    .addGroup(modificaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel45)
                        .addComponent(edada2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(55, 55, 55)
                    .addGroup(modificaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel46)
                        .addComponent(nocuentaa2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(114, 114, 114)
                    .addComponent(jButton4)
                    .addContainerGap(220, Short.MAX_VALUE))
                .addGroup(modificaralumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificaralumnoLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(nombrea2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(618, Short.MAX_VALUE)))
            );

            javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
            jtreedecano.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
            jtreedecano.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jtreedecanoMouseClicked(evt);
                }
            });
            jScrollPane3.setViewportView(jtreedecano);

            javax.swing.GroupLayout listarLayout = new javax.swing.GroupLayout(listar.getContentPane());
            listar.getContentPane().setLayout(listarLayout);
            listarLayout.setHorizontalGroup(
                listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listarLayout.createSequentialGroup()
                    .addGap(241, 241, 241)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(350, Short.MAX_VALUE))
            );
            listarLayout.setVerticalGroup(
                listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listarLayout.createSequentialGroup()
                    .addGap(110, 110, 110)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(142, Short.MAX_VALUE))
            );

            jMenuItem8.setText("Modificar");
            jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem8ActionPerformed(evt);
                }
            });
            crud.add(jMenuItem8);

            jMenuItem9.setText("Eliminar");
            jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem9ActionPerformed(evt);
                }
            });
            crud.add(jMenuItem9);

            jLabel47.setText("Cant alumnos");

            jLabel48.setText("Nombre clase");

            jLabel49.setText("Descripcion");

            jLabel50.setText("Usuario");

            jLabel51.setText("Contrassena");

            titulaciondo1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    titulaciondo1ActionPerformed(evt);
                }
            });

            jLabel52.setText("Nombre");

            jLabel53.setText("Apellido");

            jLabel54.setText("Titulacion P");

            jLabel55.setText("Titulacion maestria");

            jButton6.setText("Modificar");
            jButton6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton6ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout modificardocenteLayout = new javax.swing.GroupLayout(modificardocente.getContentPane());
            modificardocente.getContentPane().setLayout(modificardocenteLayout);
            modificardocenteLayout.setHorizontalGroup(
                modificardocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificardocenteLayout.createSequentialGroup()
                    .addContainerGap(393, Short.MAX_VALUE)
                    .addComponent(jButton6)
                    .addGap(309, 309, 309))
                .addGroup(modificardocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificardocenteLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(modificardocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(modificardocenteLayout.createSequentialGroup()
                                .addGroup(modificardocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(modificardocenteLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(modificardocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel53)
                                            .addComponent(jLabel52)))
                                    .addComponent(jLabel55)
                                    .addComponent(jLabel54)
                                    .addComponent(jLabel47)
                                    .addComponent(jLabel48)
                                    .addComponent(jLabel49)
                                    .addComponent(jLabel50)
                                    .addComponent(jLabel51))
                                .addGap(54, 54, 54)
                                .addGroup(modificardocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titulaciondo1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apellidodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cantalumnosdo1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreclasedo1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(titulacionmdo1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombredo1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(descripciondo1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usuariodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(modificardocenteLayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(contrasenado1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(146, Short.MAX_VALUE)))
            );
            modificardocenteLayout.setVerticalGroup(
                modificardocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificardocenteLayout.createSequentialGroup()
                    .addContainerGap(786, Short.MAX_VALUE)
                    .addComponent(jButton6)
                    .addGap(40, 40, 40))
                .addGroup(modificardocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificardocenteLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(modificardocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel52)
                            .addComponent(nombredo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(modificardocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(modificardocenteLayout.createSequentialGroup()
                                .addGroup(modificardocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(modificardocenteLayout.createSequentialGroup()
                                        .addGroup(modificardocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel53)
                                            .addComponent(apellidodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel54))
                                    .addComponent(titulaciondo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addComponent(jLabel55))
                            .addComponent(titulacionmdo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(modificardocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel47)
                            .addComponent(cantalumnosdo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(modificardocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel48)
                            .addComponent(nombreclasedo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(modificardocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel49)
                            .addComponent(descripciondo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(modificardocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usuariodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel50))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(modificardocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contrasenado1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel51))
                        .addGap(97, 97, 97)))
            );

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jMenu1.setText("Login");

            jMenuItem2.setText("Login");
            jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem2ActionPerformed(evt);
                }
            });
            jMenu1.add(jMenuItem2);

            jMenuItem3.setText("Logout");
            jMenu1.add(jMenuItem3);

            jMenuBar1.add(jMenu1);

            jMenu2.setText("Docente");
            jMenu2.setEnabled(false);
            jMenu2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenu2ActionPerformed(evt);
                }
            });

            jMenuItem1.setText("Aplicar Pruebas");
            jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem1ActionPerformed(evt);
                }
            });
            jMenu2.add(jMenuItem1);

            jMenuBar1.add(jMenu2);

            jMenu3.setText("Alumno");
            jMenu3.setEnabled(false);

            jMenuItem5.setText("Ver notas");
            jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem5ActionPerformed(evt);
                }
            });
            jMenu3.add(jMenuItem5);

            jMenuItem6.setText("Modificar Informacion");
            jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem6ActionPerformed(evt);
                }
            });
            jMenu3.add(jMenuItem6);

            jMenuBar1.add(jMenu3);

            jMenu5.setText("Decano");
            jMenu5.setEnabled(false);
            jMenu5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenu5ActionPerformed(evt);
                }
            });

            jMenuItem7.setText("VerListaddos");
            jMenu5.add(jMenuItem7);

            jMenuBar1.add(jMenu5);

            jMenu6.setText("CEO");
            jMenu6.setEnabled(false);
            jMenuBar1.add(jMenu6);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 570, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 437, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jbingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbingresarMouseClicked
        boolean flag = false;

        for (int i = 0; i < listaceo.size(); i++) {
            if (user.getText().equals(listaceo.get(i).getUsuario()) & contra.getText().equals(listaceo.get(i).getContrasena())) {
                jMenu6.setEnabled(true);
                user.setText("");
                contra.setText("");
                login.setVisible(false);
                flag = true;
            }
        }
        for (int i = 0; i < listadecano.size(); i++) {
            if (user.getText().equals(listadecano.get(i).getUsuario()) & contra.getText().equals(listadecano.get(i).getContrasena())) {
                jMenu5.setEnabled(true);
                user.setText("");
                contra.setText("");
                login.setVisible(false);
                flag = true;
            }
        }
        for (int i = 0; i < listadocente.size(); i++) {
            if (user.getText().equals(listadocente.get(i).getUsuario()) & contra.getText().equals(listadocente.get(i).getContrasena())) {
                jMenu2.setEnabled(true);
                user.setText("");
                contra.setText("");
                login.setVisible(false);
                flag = true;
            }
        }
        for (int i = 0; i < listaalumnos.size(); i++) {
            if (user.getText().equals(listaalumnos.get(i).getUsuario()) & contra.getText().equals(listaalumnos.get(i).getContrasena())) {
                jMenu3.setEnabled(true);
                nombrea = listaalumnos.get(i).getNombre();
                user.setText("");
                contra.setText("");
                login.setVisible(false);
                flag = true;
            }
        }
        if (user.getText().equals("david") & contra.getText().equals("1234")) {
            jMenu2.setEnabled(true);
            user.setText("");
            contra.setText("");
            login.setVisible(false);
            flag = true;
        }
        if (flag = false) {
            JOptionPane.showMessageDialog(this, "Usuario Incorrecto\n Cree un uUsuario");
            user.setText("");
            contra.setText("");
        }

    }//GEN-LAST:event_jbingresarMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        abreL();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jbnuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbnuevoMouseClicked
        String eu = JOptionPane.showInputDialog("Que tipo de usuario desea es:(Docente,Decano,CEO,Alumno)");
        if (eu.equals("Docente")) {
            abreI();
        } else if (eu.equals("Decano")) {
            abreIdecano();

        } else if (eu.equals("CEO")) {
            abreIceo();
        } else if (eu.equals("Alumno")) {

        }


    }//GEN-LAST:event_jbnuevoMouseClicked

    private void titulaciondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titulaciondoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titulaciondoActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        listadocente.add(new docente(nombredo.getText(), apellidodo.getText(), titulaciondo.getText(), titulacionmdo.getText(), cantalumnosdo.getText(), nombreclasedo.getText(), descripciondo.getText(), usuariodo.getText(), contrasenado.getText()));

        nombredo.setText("");

        apellidodo.setText("");
        titulaciondo.setText("");
        titulacionmdo.setText("");
        cantalumnosdo.setText("");
        nombreclasedo.setText("");
        descripciondo.setText("");
        usuariodo.setText("");
        contrasenado.setText("");
    }//GEN-LAST:event_jButton1MouseClicked

    private void idcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idcActionPerformed

    private void anoscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoscActionPerformed

    private void edadcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadcActionPerformed

    private void titulacioncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titulacioncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titulacioncActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        listaceo.add(new ceo(nombrec.getText(), apellidoc.getText(), titulacionc.getText(), Integer.parseInt(idc.getText()), Integer.parseInt(anosc.getText()), Integer.parseInt(edadc.getText()), usuarioc.getText(), contrasenac.getText()));

        nombrec.setText("");
        apellidoc.setText("");
        titulacionc.setText("");
        idc.setText("");
        anosc.setText("");
        edadc.setText("");
        usuarioc.setText("");
        contrasenac.setText("");
    }//GEN-LAST:event_jButton2MouseClicked

    private void edadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadeActionPerformed

    private void titulaciondeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titulaciondeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titulaciondeActionPerformed

    private void iddeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iddeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iddeActionPerformed

    private void usuariodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariodeActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        listadecano.add(new decano(nombrede.getText(), apellidode.getText(), titulacionde.getText(), Integer.parseInt(idde.getText()), Integer.parseInt(edade.getText()), titulacionude.getText(), titulacionmde.getText(), usuariode.getText(), contrasenade.getText()));
        nombrede.setText("");
        apellidode.setText("");
        titulacionde.setText("");
        idde.setText("");
        edade.setText("");
        titulacionude.setText("");
        titulacionmde.setText("");
        usuariode.setText("");
        contrasenade.setText("");
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        listaalumnos.add(new alumnos(carreraa.getText(), apellidoa.getText(), Integer.parseInt(numeroa.getText()), carreraa.getText(), Integer.parseInt(anoa.getText()), Integer.parseInt(canta.getText()), usuarioa.getText(), contrasenaa.getText()));
        carreraa.setText("");
        apellidoa.setText("");
        numeroa.setText("");
        carreraa.setText("");
        anoa.setText("");
        canta.setText("");
        usuarioa.setText("");
        contrasenaa.setText("");
    }//GEN-LAST:event_jButton5MouseClicked

    private void cantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ArrayList<prueba> lp = new ArrayList();
        DefaultListModel modelo = (DefaultListModel) jla.getModel();
        for (int i = 0; i < listaalumnos.size(); i++) {
            modelo.addElement(new alumnos(listaalumnos.get(i).getNombre(), listaalumnos.get(i).getApellido(), listaalumnos.get(i).getNumerocuenta(), listaalumnos.get(i).getCarrera(), listaalumnos.get(i).getAnocursa(), listaalumnos.get(i).getCantidaddeclasesfaltantes(), listaalumnos.get(i).getUsuario(), listaalumnos.get(i).getContrasena(), lp));
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jlaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlaMouseClicked
        if (jla.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                aplicarprueba.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jlaMouseClicked

    private void jMenuItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseClicked

    }//GEN-LAST:event_jMenuItem4MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        if (jla.getSelectedIndex() >= 0) {
            String nombre = JOptionPane.showInputDialog("");
            String nota = JOptionPane.showInputDialog("");
            prueba prueba = new prueba(nombre, nota);
            ArrayList<prueba> lp = new ArrayList();
            lp.add(prueba);
            DefaultListModel modelo = (DefaultListModel) jla.getModel();
            ((alumnos) modelo.get(jla.getSelectedIndex())).setLp(lp);
        }

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        for (int i = 0; i < listaalumnos.size(); i++) {
            for (int j = 0; j < listaalumnos.get(i).getLp().size(); j++) {

                if (listaalumnos.get(i).getNombre().equals(nombrea)) {
                    Object[] newrow = {listaalumnos.get(i).getLp().get(i).getNombre(), listaalumnos.get(i).getLp().get(i).getPuntuaje()};
                    DefaultTableModel modelo
                            = (DefaultTableModel) tabla1.getModel();
                    modelo.addRow(newrow);
                    tabla1.setModel(modelo);
                }
            }
        }
        abrevernota();

        //tf_edad_maxima.setText(maxima_edad());               

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        abrealumnos();
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        abremodi();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed

        DefaultTreeModel m = (DefaultTreeModel) jtreedecano.getModel();
        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodo_docente;
        for (int i = 0; i < listadocente.size(); i++) {
            nodo_docente
                    = new DefaultMutableTreeNode(
                            new docente(listadocente.get(i).getNombre(), listadocente.get(i).getApellido(), listadocente.get(i).getTitulo(), listadocente.get(i).getTitulomaestria(), listadocente.get(i).getCantidaddealumnosmax(), listadocente.get(i).getNombreclase(), listadocente.get(i).getDescripcion(), listadocente.get(i).getUsuario(), listadocente.get(i).getContrasena()
                            )
                    );

            DefaultMutableTreeNode alumno;
            alumno = new DefaultMutableTreeNode(new alumnos());

            nodo_docente.add(alumno);
            raiz.add(nodo_docente);
            m.reload();
            abreli();
        }
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        DefaultTreeModel m = (DefaultTreeModel) jtreedecano.getModel();
        m.removeNodeFromParent(nodo_seleccionado);
        m.reload();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jtreedecanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtreedecanoMouseClicked
        if (evt.isMetaDown()) {
            //seleccionar un nodo con click derecho
            int row = jtreedecano.getClosestRowForLocation(
                    evt.getX(), evt.getY());
            jtreedecano.setSelectionRow(row);
            Object v1 = jtreedecano.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;

            if (nodo_seleccionado.getUserObject() instanceof docente) {
                docente_seleccionada
                        = (docente) nodo_seleccionado.
                                getUserObject();
                crud.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jtreedecanoMouseClicked

    private void titulaciondo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titulaciondo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titulaciondo1ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        abremi();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultTreeModel m = (DefaultTreeModel) jtreedecano.getModel();
 DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) m.getRoot();
        docente d = new docente(nombredo1.getText(), apellidodo1.getText(), titulaciondo1.getText(), titulacionmdo.getText(), cantalumnosdo1.getText(), nombreclasedo1.getText(), descripciondo1.getText(), usuariodo1.getText(), contrasenado1.getText());
        DefaultMutableTreeNode nodo_docente;
        nodo_docente
                = new DefaultMutableTreeNode(
                        new docente(nombredo1.getText(), apellidodo1.getText(), titulaciondo1.getText(), titulacionmdo.getText(), cantalumnosdo1.getText(), nombreclasedo1.getText(), descripciondo1.getText(), usuariodo1.getText(), contrasenado1.getText()));
        
        m.removeNodeFromParent(nodo_seleccionado);
        raiz.add(nodo_docente);
            m.reload();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    private void abreL() {
        login.setModal(true);
        login.pack();
        login.setLocationRelativeTo(this);
        login.setVisible(true);
    }

    private void abreI() {
        ingresar.setModal(true);
        ingresar.pack();
        ingresar.setLocationRelativeTo(this);
        ingresar.setVisible(true);
    }

    private void abreIceo() {
        ingresarceo.setModal(true);
        ingresarceo.pack();
        ingresar.setLocationRelativeTo(this);
        ingresarceo.setVisible(true);
    }

    private void abreIdecano() {
        ingresardecano.setModal(true);
        ingresardecano.pack();
        ingresardecano.setLocationRelativeTo(this);
        ingresardecano.setVisible(true);
    }

    private void abrealumnos() {
        alumnos.setModal(true);
        alumnos.pack();
        alumnos.setLocationRelativeTo(this);
        alumnos.setVisible(true);
    }

    private void abrevernota() {
        vernota.setModal(true);
        vernota.pack();
        vernota.setLocationRelativeTo(this);
        vernota.setVisible(true);
    }

    private void abremodi() {
        modificaralumno.setModal(true);
        modificaralumno.pack();
        modificaralumno.setLocationRelativeTo(this);
        modificaralumno.setVisible(true);
    }

    private void abreli() {
        listar.setModal(true);
        listar.pack();
        listar.setLocationRelativeTo(this);
        listar.setVisible(true);
    }

    private void abremi() {
        modificardocente.setModal(true);
        modificardocente.pack();
        modificardocente.setLocationRelativeTo(this);
        modificardocente.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog alumnos;
    private javax.swing.JTextField anoa;
    private javax.swing.JTextField anosc;
    private javax.swing.JTextField apellidoa;
    private javax.swing.JTextField apellidoa2;
    private javax.swing.JTextField apellidoc;
    private javax.swing.JTextField apellidode;
    private javax.swing.JTextField apellidodo;
    private javax.swing.JTextField apellidodo1;
    private javax.swing.JPopupMenu aplicarprueba;
    private javax.swing.JTextField canta;
    private javax.swing.JTextField cantalumnosdo;
    private javax.swing.JTextField cantalumnosdo1;
    private javax.swing.JTextField carreraa;
    private javax.swing.JTextField contra;
    private javax.swing.JTextField contrasenaa;
    private javax.swing.JTextField contrasenac;
    private javax.swing.JTextField contrasenade;
    private javax.swing.JTextField contrasenado;
    private javax.swing.JTextField contrasenado1;
    private javax.swing.JPopupMenu crud;
    private javax.swing.JTextField descripciondo;
    private javax.swing.JTextField descripciondo1;
    private javax.swing.JTextField edada2;
    private javax.swing.JTextField edadc;
    private javax.swing.JTextField edade;
    private javax.swing.JTextField idc;
    private javax.swing.JTextField idde;
    private javax.swing.JDialog ingresar;
    private javax.swing.JDialog ingresaralumno;
    private javax.swing.JDialog ingresarceo;
    private javax.swing.JDialog ingresardecano;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbingresar;
    private javax.swing.JButton jbnuevo;
    private javax.swing.JList<String> jla;
    private javax.swing.JTree jtreedecano;
    private javax.swing.JDialog listar;
    private javax.swing.JDialog login;
    private javax.swing.JDialog modificaralumno;
    private javax.swing.JDialog modificardocente;
    private javax.swing.JTextField nocuentaa2;
    private javax.swing.JTextField nombrea1;
    private javax.swing.JTextField nombrea2;
    private javax.swing.JTextField nombrec;
    private javax.swing.JTextField nombreclasedo;
    private javax.swing.JTextField nombreclasedo1;
    private javax.swing.JTextField nombrede;
    private javax.swing.JTextField nombredo;
    private javax.swing.JTextField nombredo1;
    private javax.swing.JTextField numeroa;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField titulacionc;
    private javax.swing.JTextField titulacionde;
    private javax.swing.JTextField titulaciondo;
    private javax.swing.JTextField titulaciondo1;
    private javax.swing.JTextField titulacionmde;
    private javax.swing.JTextField titulacionmdo;
    private javax.swing.JTextField titulacionmdo1;
    private javax.swing.JTextField titulacionude;
    private javax.swing.JTextField user;
    private javax.swing.JTextField usuarioa;
    private javax.swing.JTextField usuarioc;
    private javax.swing.JTextField usuariode;
    private javax.swing.JTextField usuariodo;
    private javax.swing.JTextField usuariodo1;
    private javax.swing.JDialog vernota;
    // End of variables declaration//GEN-END:variables
ArrayList<ceo> listaceo = new ArrayList();
    ArrayList<decano> listadecano = new ArrayList();
    ArrayList<docente> listadocente = new ArrayList();
    ArrayList<alumnos> listaalumnos = new ArrayList();
    String nombrea;
    DefaultMutableTreeNode nodo_seleccionado;
    docente docente_seleccionada;

}
